version: '3.9'
services:
  forcast-mvc:
    image: htflynn/forcast-mvc:0.0.1.RELEASE
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - forcast-db
    networks:
      - forcast-network
    environment:
      DB_USER: postgres
      DB_HOST: forcast-db 
      DB_NAME: forcast
      DB_PASSWORD: docker
      DB_PORT: 5432

  forcast-db:
    image: htflynn/forcast-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - forcast-network
      
networks:
  forcast-network: