name: CI/CD Pipeline for AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push MVC Image
        run: |
          docker build -t htflynn/forecast-mvc:latest -f Dockerfile.mvc .
          docker push htflynn/forecast-mvc:latest

      - name: Build and Push Database Image
        run: |
          docker build -t htflynn/forecast-db:latest -f Dockerfile.db .
          docker push htflynn/forecast-db:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group myAKSResourceGroup --name myAKSCluster

      - name: Update MVC Deployment
        run: |
          kubectl set image deployment/forecast-mvc forecast-mvc=htflynn/forecast-mvc:latest
          
      - name: Update Database Deployment
        run: |
          kubectl set image deployment/forecast-db forecast-db=htflynn/forecast-db:latest
